#!/bin/bash
# set all this to latest stable release
VL="1.3.224.1"
SC="2022.2"
DXSC="1.7.2207"
RHH="3.11.5"

# This should be the same
# https://github.com/LunarG/VulkanTools/tree/master/submodules
JC="f700fe455940d4d325c088b9174a173e130e0fa8"

